// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmt7r_XRuFfz_TKSLDTn7j0uO8AgibDsY',
    appId: '1:239130950442:web:5c8d0ff9aee2b126577c53',
    messagingSenderId: '239130950442',
    projectId: 'notificacioncalenelectoral',
    authDomain: 'notificacioncalenelectoral.firebaseapp.com',
    databaseURL: 'https://notificacioncalenelectoral.firebaseio.com',
    storageBucket: 'notificacioncalenelectoral.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCe09q0RZ4hn-gZKQqOqd1gQVb-JJKaJg',
    appId: '1:239130950442:android:267a6f849b7012d3577c53',
    messagingSenderId: '239130950442',
    projectId: 'notificacioncalenelectoral',
    databaseURL: 'https://notificacioncalenelectoral.firebaseio.com',
    storageBucket: 'notificacioncalenelectoral.appspot.com',
  );
}
